export const PRODUCTS = [
  {
    name: "Apple",
    description: "Fresh red apple",
    image: "/assets/images/apple.jpg",
  },
  {
    name: "Banana",
    description: "Organic bananas",
    image: "/assets/images/banana.jpg",
  },
  {
    name: "Cherry",
    description: "Organic bananas",
    image: "/assets/images/cherry.jpeg",
  },
  {
    name: "Abricot",
    description: "Organic bananas",
    image: "/assets/images/abricot.jpeg",
  },
  {
    name: "Pineapple",
    description: "Organic bananas",
    image: "/assets/images/pineapple.jpeg",
  },
  {
    name: "Strawberry",
    description: "Organic bananas",
    image: "/assets/images/strawberry.jpeg",
  },

  {
    name: "Banana",
    description: "Organic bananas",
    image: "/assets/images/banana.jpg",
  },
  {
    name: "Apple",
    description: "Fresh red apple",
    image: "/assets/images/apple.jpg",
  },
  {
    name: "Abricot",
    description: "Organic bananas",
    image: "/assets/images/abricot.jpeg",
  },
  {
    name: "Cherry",
    description: "Organic bananas",
    image: "/assets/images/cherry.jpeg",
  },
  {
    name: "Strawberry",
    description: "Organic bananas",
    image: "/assets/images/strawberry.jpeg",
  },
  {
    name: "Pineapple",
    description: "Organic bananas",
    image: "/assets/images/pineapple.jpeg",
  },
  {
    name: "Cherry",
    description: "Organic bananas",
    image: "/assets/images/cherry.jpeg",
  },
  {
    name: "Strawberry",
    description: "Organic bananas",
    image: "/assets/images/strawberry.jpeg",
  },
  {
    name: "Pineapple",
    description: "Organic bananas",
    image: "/assets/images/pineapple.jpeg",
  },
  {
    name: "Strawberry",
    description: "Organic bananas",
    image: "/assets/images/strawberry.jpeg",
  },
  {
    name: "Pineapple",
    description: "Organic bananas",
    image: "/assets/images/pineapple.jpeg",
  },
];

export const CATEGORIES = [
  "Fresh",
  "Beverage",
  "Dairy",
  "Snacks",
  "Snacks",
  "Snacks",
  "Snacks",
  "Fresh",
  "Beverage",
  "Dairy",
  "Snacks",
  "Snacks",
  "Snacks",
  "Snacks",
  "Fresh",
  "Beverage",
  "Dairy",
  "Snacks",
  "Snacks",
  "Snacks",
  "Snacks",
  "Fresh",
  "Beverage",
  "Dairy",
  "Snacks",
  "Snacks",
  "Snacks",
  "Snacks",
  "Fresh",
  "Beverage",
  "Dairy",
  "Snacks",
  "Snacks",
  "Snacks",
  "Snacks",
  "Fresh",
];
